// React_JS/task-list/src/components/Register.jsx
import React from "react";

export default function Register() {
  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col-md-12 mt-5">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h1>Register</h1>
          </div>
        </div>
        <div className="row">
          <div className="col-md-12">
            <section className="vh-100">
              <div className="container-fluid h-custom">
                <div className="row d-flex justify-content-center align-items-center h-100">
                  <div className="col-md-9 col-lg-6 col-xl-5">
                    <img
                      src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                      className="img-fluid"
                      alt="Sample image"
                    />
                  </div>
                  <div className="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form>
                      <div className="form-outline mb-4">
                        <input
                          type="email"
                          id="form3Example3"
                          className="form-control form-control-lg"
                          placeholder="Enter a valid email address"
                        />
                        <label className="form-label" htmlFor="form3Example3">
                          Email address
                        </label>
                      </div>

                      <div className="form-outline mb-3">
                        <input
                          type="password"
                          id="form3Example4"
                          className="form-control form-control-lg"
                          placeholder="Enter password"
                        />
                        <label className="form-label" htmlFor="form3Example4">
                          Password
                        </label>
                      </div>

                      <div className="d-flex justify-content-between align-items-center">
                        <div className="form-check mb-0">
                          <input
                            className="form-check-input me-2"
                            type="checkbox"
                            value=""
                            id="form2Example3"
                          />
                          <label
                            className="form-check-label"
                            htmlFor="form2Example3"
                          >
                            Remember me
                          </label>
                        </div>
                        <a href="#!" className="text-body">
                          Forgot password?
                        </a>
                      </div>

                      <div className="text-center text-lg-start mt-4 pt-2">
                        <button
                          type="button"
                          className="btn btn-primary btn-lg"
                        >
                          Login
                        </button>
                        <p className="small fw-bold mt-2 pt-1 mb-0">
                          Don't have an account?{" "}
                          <a href="#!" className="link-danger">
                            Register
                          </a>
                        </p>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}

// Angular/daily-task-list/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { UserHandlingService } from '../../services/user-handling.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrl: './register.component.css',
})
export class RegisterComponent {
  btnText: string = 'Register';
  btnSubmit: boolean = false;
  succMsg: boolean = false;

  constructor(private handleUser: UserHandlingService) {}
  registerForm = new FormGroup({
    name: new FormControl('', [Validators.required, Validators.minLength(5)]),
    email: new FormControl('', [
      Validators.required,
      Validators.email,
      Validators.min(6),
    ]),
    password: new FormControl('', [
      Validators.required,
      Validators.minLength(8),
    ]),
  });

  registerUser() {
    this.btnText = 'Processing...';
    this.btnSubmit = true;
    this.handleUser.registerUser(this.registerForm.value).subscribe((res) => {
      this.btnText = 'Register';
      this.btnSubmit = false;
      this.succMsg = true;
      console.log(res);
    });
  }

  get getName() {
    return this.registerForm.get('name');
  }
  get getEmail() {
    return this.registerForm.get('email');
  }
  get getPassword() {
    return this.registerForm.get('password');
  }
}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section class="vh-100">
        <div class="container-fluid h-custom">
          <h1 class="text-center mt-5 mb-3 text-info">Register</h1>
          <div
            class="row d-flex justify-content-center align-items-center h-100"
          >
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid"
                alt="Sample image"
              />
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <form [formGroup]="registerForm" (ngSubmit)="registerUser()">
                <!-- Name input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3">Name</label>
                  <input
                    type="text"
                    id="form3Example3"
                    class="form-control form-control-lg"
                    placeholder="Enter a valid name"
                    formControlName="name"
                  />
                  <div *ngIf="getName?.invalid">
                    <p
                      class="text-danger"
                      *ngIf="getName?.invalid && getName?.touched && getName?.errors?.['required']"
                    >
                      Name is required
                    </p>
                    <p
                      class="text-danger"
                      *ngIf="getName?.errors?.['minlength']"
                    >
                      Min length is 5
                    </p>
                  </div>
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3"
                    >Email address</label
                  >
                  <input
                    type="email"
                    id="form3Example3"
                    class="form-control form-control-lg"
                    formControlName="email"
                    placeholder="Enter a valid email address"
                  />
                  <p
                    class="text-danger"
                    *ngIf="getEmail?.invalid && getEmail?.touched"
                  >
                    Invalid Email Address
                  </p>
                </div>

                <!-- Password input -->
                <div class="form-outline mb-3">
                  <label class="form-label" for="form3Example4">Password</label>
                  <input
                    type="password"
                    id="form3Example4"
                    class="form-control form-control-lg"
                    placeholder="Enter password"
                    formControlName="password"
                  />
                  <p
                    class="text-danger"
                    *ngIf="getPassword?.invalid && getPassword?.touched && getPassword?.errors?.['required']"
                  >
                    Password is required
                  </p>
                  <p
                    class="text-danger"
                    *ngIf="getPassword?.errors?.['minlength']"
                  >
                    Min length is 8
                  </p>
                </div>

                <div class="d-flex justify-content-between align-items-center">
                  <!-- Checkbox -->
                  <div class="form-check mb-0">
                    <input
                      class="form-check-input me-2"
                      type="checkbox"
                      value=""
                      id="form2Example3"
                    />
                    <label class="form-check-label" for="form2Example3">
                      Remember me
                    </label>
                  </div>
                  <a href="#!" class="text-body">Forgot password?</a>
                </div>

                <div class="text-center text-lg-start mt-4 pt-2">
                  <button
                    type="submit"
                    class="btn btn-primary btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem"
                    [disabled]="registerForm.invalid"
                  >
                    <span
                      *ngIf="btnSubmit"
                      class="spinner-border spinner-border-sm"
                      aria-hidden="true"
                    ></span>
                    <span role="status">{{ btnText }}</span>
                  </button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">
                    Already have account
                    <a routerLink="/login" class="link-danger">Login</a>
                  </p>
                </div>
                <div class="alert alert-success" *ngIf="succMsg">
                  User Registered Successfully
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
