// Angular/daily-task-list/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { UserHandlingService } from '../../services/user-handling.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  errorMsg = '';
  btnText: string = 'Login';
  btnSubmit: boolean = false;
  loginForm = new FormGroup({
    email: new FormControl(''),
    password: new FormControl(''),
  });

  constructor(private handleUser: UserHandlingService, private router: Router) {
    if (localStorage.getItem('token')) {
      router.navigate(['dashboard']);
    }
  }

  loginUser() {
    this.btnText = 'Procssing...';
    this.btnSubmit = true;

    this.handleUser.loginUser(this.loginForm.value).subscribe((res: any) => {
      console.log(res);
      if (res.token) {
        localStorage.setItem('token', res.token);
        localStorage.setItem('user', JSON.stringify(res.user));
        this.router.navigate(['dashboard']);
      } else {
        this.btnText = 'Login';
        this.btnSubmit = false;
        this.errorMsg = res.message;
      }
    });
  }
}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section class="vh-100">
        <div class="container-fluid h-custom">
          <h1 class="text-center mt-5 mb-3 text-info">Login</h1>
          <div
            class="row d-flex justify-content-center align-items-center h-100"
          >
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid"
                alt="Sample image"
              />
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <form [formGroup]="loginForm" (ngSubmit)="loginUser()">
                <!-- Email input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3"
                    >Email address</label
                  >
                  <input
                    type="email"
                    id="form3Example3"
                    class="form-control form-control-lg"
                    placeholder="Enter a valid email address"
                    formControlName="email"
                  />
                </div>

                <!-- Password input -->
                <div class="form-outline mb-3">
                  <label class="form-label" for="form3Example4">Password</label>
                  <input
                    type="password"
                    id="form3Example4"
                    class="form-control form-control-lg"
                    placeholder="Enter password"
                    formControlName="password"
                  />
                </div>

                <div class="d-flex justify-content-between align-items-center">
                  <!-- Checkbox -->
                  <div class="form-check mb-0">
                    <input
                      class="form-check-input me-2"
                      type="checkbox"
                      value=""
                      id="form2Example3"
                    />
                    <label class="form-check-label" for="form2Example3">
                      Remember me
                    </label>
                  </div>
                  <a href="#!" class="text-body">Forgot password?</a>
                </div>

                <div class="text-center text-lg-start mt-4 pt-2">
                  <button
                    type="submit"
                    class="btn btn-primary btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem"
                  >
                    <span
                      *ngIf="btnSubmit"
                      class="spinner-border spinner-border-sm mr-2"
                      aria-hidden="true"
                    ></span>
                    {{btnText}}
                  </button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">
                    Don't have an account?
                    <a routerLink="/register" class="link-danger">Register</a>
                  </p>
                </div>
                <div class="alert alert-danger" *ngIf="errorMsg">
                  {{ errorMsg }}
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

// React_JS/task-list/src/components/Login.jsx
import React from "react";

export default function Login() {
  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col-md-12 mt-5">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h1>Login</h1>
          </div>
        </div>
        <div className="row">
          <div className="col-md-12">
            <section className="vh-100">
              <div className="container-fluid h-custom">
                <div className="row d-flex justify-content-center align-items-center h-100">
                  <div className="col-md-9 col-lg-6 col-xl-5">
                    <img
                      src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                      className="img-fluid"
                      alt="Sample image"
                    />
                  </div>
                  <div className="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form>
                      <div className="form-outline mb-4">
                        <input
                          type="email"
                          id="form3Example3"
                          className="form-control form-control-lg"
                          placeholder="Enter a valid email address"
                        />
                        <label className="form-label" htmlFor="form3Example3">
                          Email address
                        </label>
                      </div>

                      <div className="form-outline mb-3">
                        <input
                          type="password"
                          id="form3Example4"
                          className="form-control form-control-lg"
                          placeholder="Enter password"
                        />
                        <label className="form-label" htmlFor="form3Example4">
                          Password
                        </label>
                      </div>

                      <div className="d-flex justify-content-between align-items-center">
                        <div className="form-check mb-0">
                          <input
                            className="form-check-input me-2"
                            type="checkbox"
                            value=""
                            id="form2Example3"
                          />
                          <label
                            className="form-check-label"
                            htmlFor="form2Example3"
                          >
                            Remember me
                          </label>
                        </div>
                        <a href="#!" className="text-body">
                          Forgot password?
                        </a>
                      </div>

                      <div className="text-center text-lg-start mt-4 pt-2">
                        <button
                          type="button"
                          className="btn btn-primary btn-lg"
                        >
                          Login
                        </button>
                        <p className="small fw-bold mt-2 pt-1 mb-0">
                          Don't have an account?{" "}
                          <a href="#!" className="link-danger">
                            Register
                          </a>
                        </p>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
