// Angular/my-first-project/src/app/register/register.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { AuthUserService } from '../services/auth-user.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {
  constructor (private userAuth: AuthUserService) {  } 
  successMessage = "";
  errorMessage = "";
  previewImg:any = "";
  registerForm = new FormGroup({
    email: new FormControl("", [
      Validators.required, 
      Validators.email,
      Validators.minLength(10)
    ]),
    password: new FormControl("", [
      Validators.required,
      Validators.minLength(8),
      Validators.maxLength(20)
    ]),
    full_name: new FormControl("", Validators.required)
  });

  registerUser() {
    let res:any = this.userAuth.checkEmail(this.registerForm.value.email);
    if(res) {
      console.log("Email already exist");
      
    } else {
      this.userAuth.registerUser(this.registerForm.value);
      console.log("User registered successfully");
      
    }
    
  }

  get checkEmail() {
    return this.registerForm.get("email");
  }
  
  get checkPassword() {
    return this.registerForm.get("password");
  }
  
  get checkName() {
    return this.registerForm.get("full_name");
  }

  previewFile(input:any) {
    let file = input.target.files[0];
    this.previewImg = URL.createObjectURL(file);
    // let reader = new FileReader();
    // reader.onload = () => {
    //   this.previewImg = reader.result;
    // }
    // reader.readAsDataURL(file);
    
  }
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <section class="vh-100">
                <div class="container-fluid h-custom">
                  <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-md-9 col-lg-6 col-xl-5">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                        class="img-fluid" alt="Sample image">
                    </div>
                    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                        <h1>Register</h1>
                      <form [formGroup] = "registerForm" (ngSubmit)="registerUser()">
              
                        <!-- Name input -->
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form3Example3">Full Name</label>
                          <input type="text" formControlName="full_name" class="form-control form-control-lg"
                            placeholder="Enter Name" />
                            <div class="text-danger" *ngIf="checkName?.invalid && checkName?.touched">
                                <p *ngIf="checkName?.errors?.['required']">Name is required</p>
                             
                            </div>
                        </div>
                        
                        <!-- Email input -->
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form3Example3">Email address</label>
                          <input type="email" formControlName="email" class="form-control form-control-lg"
                            placeholder="Enter a valid email address" />
                            <div class="text-danger" *ngIf="checkEmail?.invalid && checkEmail?.touched">
                                <p *ngIf="checkEmail?.errors?.['required']">Email is required</p>
                                <p *ngIf="checkEmail?.errors?.['minlength']">Min length is 10</p>
                                <p *ngIf="checkEmail?.errors?.['email']">Email not valid</p>
                            </div>
                        </div>
                        
                        <!-- File input -->
                        <div class="form-outline mb-4">
                          <label class="form-label" for="form3Example3">Email address</label>
                          <input (change)="previewFile($event)" type="file" formControlName="image" class="form-control form-control-lg" />
                          <img src="{{previewImg}}" width="200px" height="200px" alt="">
                        </div>

              
                        <!-- Password input -->
                        <div class="form-outline mb-3">
                            <label class="form-label" for="form3Example4">Password</label>
                          <input type="password" formControlName="password" class="form-control form-control-lg"
                            placeholder="Enter password" />
                            <div class="text-danger" *ngIf="checkPassword?.invalid && checkPassword?.touched">
                                <p *ngIf="checkPassword?.errors?.['required']">Email is required</p>
                                <p *ngIf="checkPassword?.errors?.['minlength']">Min length is 8</p>
                                <p *ngIf="checkPassword?.errors?.['maxlength']">Max length is 20</p>
                            </div>
                        </div>
              
                        <div class="text-center text-lg-start mt-4 pt-2">
                          <button type="submit" [disabled]="registerForm.invalid" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Register</button>
                          <p class="small fw-bold mt-2 pt-1 mb-0">Have an account? login here <a routerLink="/login"
                              class="link-danger">Login</a></p>
                        </div>
              
                      </form>
                    </div>
                  </div>
                </div>
              </section>
        </div>
    </div>
</div>

// React_JS/task-list/src/components/Register.jsx
import React from "react";

export default function Register() {
  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col-md-12 mt-5">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h1>Register</h1>
          </div>
        </div>
        <div className="row">
          <div className="col-md-12">
            <section className="vh-100">
              <div className="container-fluid h-custom">
                <div className="row d-flex justify-content-center align-items-center h-100">
                  <div className="col-md-9 col-lg-6 col-xl-5">
                    <img
                      src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                      className="img-fluid"
                      alt="Sample image"
                    />
                  </div>
                  <div className="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form>
                      <div className="form-outline mb-4">
                        <input
                          type="email"
                          id="form3Example3"
                          className="form-control form-control-lg"
                          placeholder="Enter a valid email address"
                        />
                        <label className="form-label" htmlFor="form3Example3">
                          Email address
                        </label>
                      </div>

                      <div className="form-outline mb-3">
                        <input
                          type="password"
                          id="form3Example4"
                          className="form-control form-control-lg"
                          placeholder="Enter password"
                        />
                        <label className="form-label" htmlFor="form3Example4">
                          Password
                        </label>
                      </div>

                      <div className="d-flex justify-content-between align-items-center">
                        <div className="form-check mb-0">
                          <input
                            className="form-check-input me-2"
                            type="checkbox"
                            value=""
                            id="form2Example3"
                          />
                          <label
                            className="form-check-label"
                            htmlFor="form2Example3"
                          >
                            Remember me
                          </label>
                        </div>
                        <a href="#!" className="text-body">
                          Forgot password?
                        </a>
                      </div>

                      <div className="text-center text-lg-start mt-4 pt-2">
                        <button
                          type="button"
                          className="btn btn-primary btn-lg"
                        >
                          Login
                        </button>
                        <p className="small fw-bold mt-2 pt-1 mb-0">
                          Don't have an account?{" "}
                          <a href="#!" className="link-danger">
                            Register
                          </a>
                        </p>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
